version: "3.9"

services:
  # backend api
  groceasy-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/groceasy-api
    environment:
      POSTGRES_URI: postgres://admin:secret123@postgres:5432/groceasy-db
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/groceasy-api
      - /usr/src/groceasy-api/node_modules

  # POSTGRES
  postgres:
    build: ./postgres
    environment:
      POSTGRES_PASSWORD: secret123
      POSTGRES_USER: admin
      POSTGRES_DB: groceasy-db
      POSTGRES_HOST: postgres
    ports:
      - 5432

  # REDIS
  redis:
    image: redis
    ports:
      - 6379
