###
GET  http://localhost:8000/products/list


###
GET http://localhost:8000/sellers/list

###
POST http://localhost:8000/checkout/stk


Content-Type: application/json

{
  
}


###
DELETE http://localhost:8000/products/delete HTTP/1.1

Content-Type: application/json

{
  "category": "Vegetables",
  "id": 1,
  "price": "10.00",
  "product_name": "Kale"
}